### ISSUE TITLE
Documentation Build System Issues

### ISSUE THREAD

**Issue by michael-okeefe** [cse-sim/cse#10]
This is a "catch all" issue to discuss and capture next steps with the documentation build system. We could possibly break some or all of these out into separate issues but I'll keep them as a collection for now unless someone has a strong feeling otherwise.

- [ ] Change record fields into section headers to make them linkable
- [ ] Add linkable headings
see https://docs.readthedocs.io/en/latest/getting_started.html#write-your-docs and hover over a heading.
- [ ] Fix bug in link verifier
"*.md" said [SHADEX](#shadeX).  Link did not work.  Verifier did NOT report a problem. Changed *.md to [SHADEX](#shadex) and link worked.
- [ ] Move time-stamps to the top of page(?)
- [ ] Add time-stamp for "last edited" for the source file

**Comment by chipbarnaby** [comment]
Additional issue --

documentation-coverage-report does not catch duplicate documentation entries ("in documentation more that once").

**Comment by nealkruis** [comment]
Moved these all to separate issues.
