### ISSUE TITLE
IvAirX definition and descriptions are inconsistent

### ISSUE THREAD

**Issue by hobob0t** [cse-sim/cse#113]
If I understand this line correctly:
https://github.com/cse-sim/cse/blob/56b98885a655930967e379583ebd011689495ab3/src/CNLOADS.CPP#L1400

and the documentation in https://cse-sim.github.io/cse/cse-user-manual/probe_znres.html#p_znres

Then the descriptions are inconsistent. The source code indicates that HVAC is part of ivairx, while the documentation specifically states that ivairx does not include hvac.

**Comment by chipbarnaby** [comment]
I believe the descriptions are consistent.  According to my reading of the
code, neither zn_AnAmf() nor zn_NonAnIVAmf() includes HVAC air flows.

The definitive way to investigate issues like this is to run experiments
that display hour or subhour results in user-defined reports.  I have
attached a run that does this.  In the hourly reports, the column "ACH"
shows zn_ivAirX.  The adjacent columns show heating and cooling loads.  As
you can see, the ACH values remain about the same independent of HVAC
activity.

**Comment by hobob0t** [comment]
Thanks Chip I think I see my mistake now!
