### ISSUE TITLE
Remove Windows specific headers and functions

### ISSUE THREAD

**Issue by nealkruis** [cse-sim/cse#14]
Many typedefs (e.g. `DWORD`, `UINT`) from `windows.h` can simply be redefined in a separate header file.

List of offenders discovered so far:

- [ ] `stricmp()`
- [ ] `getcwd()`
- [ ] general filesystem processes

**Comment by chipbarnaby** [comment]
Added #define ELIMINATE_WINDOWS option in cnglob.h

Provided suitable typedefs for Windows-ish types (e.g. DWORD).

Remaining compile errors fall into a few categories --
* Some character functions.  Should be replaceable with library functions.
* OS-specific IO and error functions (GetLastError etc.).  Probably need OS-specific wrappers?
* DLL interface (xmodule.h).  No DLLs currently in use.  Suggest #if-out until needed.
* A few odds/ends.

Some of the other functions mentioned above (getcwd() etc) have equivalent standard replacements and can be recoded.

**Comment by nealkruis** [comment]
See PR #146.
