### ISSUE TITLE
Remove page boundaries for .REP file by default

### ISSUE THREAD

**Issue by galanCA** [cse-sim/cse#172]
Add the options to eliminate page boundaries from the `.REP` file in order to prevent a small change from creating a number of new pages.

**Comment by chipbarnaby** [comment]
Just discovered that this capability already exists.

REPORTFILE rfPageFmt=NO turns off the page breaks.

This can be applied to the primary report file via

ALTER REPORTFILE Primary rfPageFmt = NO
