### ISSUE TITLE
Missing section reference for operators and operands

### ISSUE THREAD

**Issue by aaron-boranian** [cse-sim/cse#2]
Reference within Section 4.3.3 to another section is blank:

4.3.3 Expressions – Overview
Expressions are the parts of statements that specify values – numeric values, string values, object name values, and choice values. Expressions are composed of operators and operands, in a manner similar to many programming languages. The available operators and operands will be described in Section ___.

Looking through the document, operators are discussed in Section 4.6.3 and operands are discussed in Section 4.6.4.

**Comment by michael-okeefe** [comment]
Fixed in 1990c7b95b5ba69379756345951bd5bc1c2a6efb
