### ISSUE TITLE
Determine preprocessor values for build matrix

### ISSUE THREAD

**Issue by nealkruis** [cse-sim/cse#343]
A build is characterized by:

- Platform (Windows, MacOS, Linux)
- Target architecture size (32, 64)
- Compiler (MSVC, GCC, Clang)

We want distinctive preprocessor values for each of these. Here is my proposal:

Platform (https://sourceforge.net/p/predef/wiki/OperatingSystems/):

- `CSE_PLATFORM_WINDOWS` = `_WIN32`
- `CSE_PLATFORM_MACOS` = `__APPLE__`
- `CSE_PLATFORM_LINUX` = `__linux__`

Target architecture size (defined through CMake option):

- `CSE_ARCH_32`
- `CSE_ARCH_64`

Compiler (https://sourceforge.net/p/predef/wiki/Compilers/):

- `CSE_COMPILER_MSVC` = `_MSC_VER`
- `CSE_COMPILER_GCC` = `__GNUC__	&& !__clang__`
- `CSE_COMPILER_CLANG` = `__clang__`
- `CSE_COMPILER_APPLECLANG` = `__clang__ && __apple_build_version__`

**Comment by nealkruis** [comment]
@galanCA is this done now? or is it still unmerged?

**Comment by galanCA** [comment]
@nealkruis This is merged in main, inside [cndefns.h](https://github.com/cse-sim/cse/blob/9957cba4bd90b4a578785945e93ea34338308dad/src/cndefns.h#L16-L62)
