### ISSUE TITLE
Documentation coverage bug for multi-item groups

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#65]
The documentation coverage detectorizer is not handling item groups, see example.

Example - DHWSYS.md

wsFaucetCount=integer
wsShowerCount=integer
wsBathCount=integer
wsCWashrCount=integer
wsDWashrCount=integer

Specifies the count of fixtures served by this DHWSYS that can accommodate draws of each end use (see DHWUSE). blah blah blah

>>> The coverage report lists all of these items except wsDWashrCount as "in CSE but not documentation"

**Comment by michael-okeefe** [comment]
See https://github.com/cse-sim/cse/pull/86.
Duplicate of https://github.com/cse-sim/cse/issues/81

**Comment by michael-okeefe** [comment]
Duplicate of https://github.com/cse-sim/cse/issues/81

**Comment by galanCA** [comment]
@nealkruis This issue seems to be resolve.

**Comment by nealkruis** [comment]
Closing because this is a duplicate.
