### ISSUE TITLE
Coverage report does not detect presence of grouped items

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#81]
In some cases, several items are documented as a group.  For example --

**wsFaucetCount=*integer***\
**wsShowerCount=*integer***\
**wsBathCount=*integer***\
**wsCWashrCount=*integer***\
**wsDWashrCount=*integer***

Blah blah blah.

The coverage report shows all items except the first (wsFaucetCount) as "in CSE but not in Documentation"

Group items are used only in a few places.  If the source format needs to change to make this work, not a problem.

**Comment by michael-okeefe** [comment]
See https://github.com/cse-sim/cse/pull/86

**Comment by galanCA** [comment]
@nealkruis This issue has been merged.

**Comment by nealkruis** [comment]
@galanCA what PR was this addressed in?

**Comment by galanCA** [comment]
[PR86](https://github.com/cse-sim/cse/pull/86)

**Comment by nealkruis** [comment]
I see. I was wrong in my comments in #86 (sorry @galanCA). I was thinking you were referring to how we addressed this in the documentation coverage branch by explicitly creating sections for each of these inputs.
