### ISSUE TITLE
ERB doesn't process mathematical symbols in member table entry

### ISSUE THREAD

**Issue by tanaya-bigladder** [cse-sim/cse#85]
```
<%= member_table(
  units: "*gpm",
  legal_range: "x $\ge$ 0",
  default: "1.0",
  required: "No",
  variability: "constant") %>
```

does not render in PDF as a "greater-than-or-equal" symbol. Using the old style MD table still works:
```
**Units**   **Legal Range**         **Default**       **Required**   **Variability**
----------- ---------------------   -------------     -------------- -----------------
 gpm         x $\ge$ 0              1.0                 No             constant
```

**Comment by galanCA** [comment]
@nealkruis This issue is solve.

**Comment by galanCA** [comment]
![image](https://user-images.githubusercontent.com/17099469/161296690-6809a7b5-e3f5-4171-adee-063455541146.png)
![image](https://user-images.githubusercontent.com/17099469/161296817-0a566b71-9143-4091-8605-d00fb2cb8b5a.png)
